"""add a user_id line

迁移 ID: 098edf732b89
父迁移: 26c68a30d9f4
创建时间: 2026-02-16 14:09:51.530343

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '098edf732b89'
down_revision: str | Sequence[str] | None = '26c68a30d9f4'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aihelper_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aihelper_settings', schema=None) as batch_op:
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
