"""remove balance line

迁移 ID: a424de08f36b
父迁移: 098edf732b89
创建时间: 2026-02-16 14:23:57.884402

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

revision: str = 'a424de08f36b'
down_revision: str | Sequence[str] | None = '098edf732b89'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aihelper_settings', schema=None) as batch_op:
        batch_op.drop_column('user_balance')

    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aihelper_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_balance', mysql.FLOAT(), nullable=False))

    # ### end Alembic commands ###
