"""add is_enabled

迁移 ID: c0f7241d2442
父迁移: f1c6dd405714
创建时间: 2026-02-20 10:37:33.041082

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'c0f7241d2442'
down_revision: str | Sequence[str] | None = 'f1c6dd405714'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aihelper_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_enabled', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aihelper_settings', schema=None) as batch_op:
        batch_op.drop_column('is_enabled')

    # ### end Alembic commands ###
