"""init

迁移 ID: 26c68a30d9f4
父迁移: 
创建时间: 2026-02-16 09:44:50.550016

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '26c68a30d9f4'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aihelper_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.Column('api_key', sa.String(length=255), nullable=False),
    sa.Column('model_name', sa.String(length=255), nullable=False),
    sa.Column('user_balance', sa.Float(), nullable=False),
    sa.Column('max_length', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_aihelper_settings')),
    info={'bind_key': 'aihelper'}
    )
    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('aihelper_settings')
    # ### end Alembic commands ###
