"""add new table

迁移 ID: 6e86f985a307
父迁移: a424de08f36b
创建时间: 2026-02-16 16:40:24.260389

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '6e86f985a307'
down_revision: str | Sequence[str] | None = 'a424de08f36b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aihelper_comments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_aihelper_comments')),
    info={'bind_key': 'aihelper'}
    )
    with op.batch_alter_table('aihelper_comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_aihelper_comments_comment_id'), ['comment_id'], unique=False)

    with op.batch_alter_table('aihelper_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('system', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aihelper_settings', schema=None) as batch_op:
        batch_op.drop_column('system')

    with op.batch_alter_table('aihelper_comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_aihelper_comments_comment_id'))

    op.drop_table('aihelper_comments')
    # ### end Alembic commands ###
