"""add temperature

迁移 ID: 766a7f1e4bce
父迁移: dc9dccf815d6
创建时间: 2026-02-18 11:13:18.496759

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '766a7f1e4bce'
down_revision: str | Sequence[str] | None = 'dc9dccf815d6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aihelper_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('temperature', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aihelper_settings', schema=None) as batch_op:
        batch_op.drop_column('temperature')

    # ### end Alembic commands ###
