"""add unique to comment_id

迁移 ID: dc9dccf815d6
父迁移: 6e86f985a307
创建时间: 2026-02-16 20:42:56.642249

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'dc9dccf815d6'
down_revision: str | Sequence[str] | None = '6e86f985a307'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aihelper_comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_aihelper_comments_comment_id'))
        batch_op.create_index(batch_op.f('ix_aihelper_comments_comment_id'), ['comment_id'], unique=True)

    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aihelper_comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_aihelper_comments_comment_id'))
        batch_op.create_index(batch_op.f('ix_aihelper_comments_comment_id'), ['comment_id'], unique=False)

    # ### end Alembic commands ###
