name: Qodana Code Quality

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
      - 'releases/*'
  pull_request:

jobs:
  qodana:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Run Qodana Scan
        uses: JetBrains/qodana-action@v2026.1          # Action 版本：2026.1
        with:
          pr-mode: false
          args: --linter,jetbrains/qodana-jvm-community:2026.1   # Linter 镜像：Community for JVM 2026.1
          results-dir: ${{ runner.temp }}/qodana/results
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}

      - name: 'Upload SARIF to GitHub Code Scanning'
        if: success() || failure()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ${{ runner.temp }}/qodana/results/qodana_report.sarif.json
        
